/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package longpipescw;

import java.util.*;
/**
 *
 * @author conorfarrell
 */
public class Invoice extends javax.swing.JFrame {

    /**
     * Creates new form Invoice
     */
    public Invoice(ArrayList order) {
        initComponents();
        populate(order);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invoiceTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoiceOrderText = new javax.swing.JTextArea();
        overallCostText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invoiceTitle.setText("Invoice");

        invoiceOrderText.setColumns(20);
        invoiceOrderText.setRows(5);
        jScrollPane1.setViewportView(invoiceOrderText);

        overallCostText.setText("Overall Cost: £0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(overallCostText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(invoiceTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(invoiceTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(overallCostText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea invoiceOrderText;
    private javax.swing.JLabel invoiceTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel overallCostText;
    // End of variables declaration//GEN-END:variables
    public void populate(ArrayList order){
        invoiceTitle.setFont(invoiceTitle.getFont().deriveFont(18f));
        invoiceTitle.setHorizontalAlignment(invoiceTitle.CENTER);
        invoiceOrderText.setEditable(false);
        double overallCost = 0; // move this to the constructor 
        invoiceOrderText.setText("Order Breakdown\n\n");
        for(int i = 0; i < order.size(); i++){
           overallCost += ((Pipe)order.get(i)).totalCost;  // isnt this casting ?
           // also directly accessing variables outside of the class theya re iniated in is bad
           //we need to use a get method if we want the variable 
           invoiceOrderText.setText(invoiceOrderText.getText() + "Order #" + (i+1) + "\n");
           invoiceOrderText.setText(invoiceOrderText.getText() + "Length of pipe: " + ((Pipe)order.get(i)).lengthOfPipe + " (meters)\n");
           invoiceOrderText.setText(invoiceOrderText.getText() + "Diameter of pipe: " + ((Pipe)order.get(i)).diameterOfPipe + " (inches)\n");
           invoiceOrderText.setText(invoiceOrderText.getText() + "Grade: " + ((Pipe)order.get(i)).grade + "\n");
           invoiceOrderText.setText(invoiceOrderText.getText() + "Chemical Resistance: " + ((Pipe)order.get(i)).chemResist + "\n");
           invoiceOrderText.setText(invoiceOrderText.getText() + "Quantity: " + (int)((Pipe)order.get(i)).quantity + "\n");
           
//         Not sure this is the best way to do it, however, it works! Variables are all now stored in superclass! - Sounds wrong

           if(((Pipe)order.get(i)).colour1 != null){
               invoiceOrderText.setText(invoiceOrderText.getText() + "Colour 1: " + ((Pipe)order.get(i)).colour1 + "\n");
           }
           if(((Pipe)order.get(i)).colour2 != null){
              invoiceOrderText.setText(invoiceOrderText.getText() + "Colour 2: " + ((Pipe)order.get(i)).colour2 + "\n"); 
           }
           if(((Pipe)order.get(i)).innerInsulation != null){
               invoiceOrderText.setText(invoiceOrderText.getText() + "Inner Insulation: " + ((Pipe)order.get(i)).innerInsulation + "\n");
           }
           if(((Pipe)order.get(i)).outterReinforcement != null){
               invoiceOrderText.setText(invoiceOrderText.getText() + "Outer Reinforcement: " + ((Pipe)order.get(i)).outterReinforcement + "\n");
           }
           
           invoiceOrderText.setText(invoiceOrderText.getText() + "Total cost: £" + ((Pipe)order.get(i)).totalCost + "\n");
           invoiceOrderText.setText(invoiceOrderText.getText() + "\n");
        }
        overallCost = (double) Math.round(overallCost * 100) / 100;
        overallCostText.setText("Overall cost: £" + overallCost + "\n");
        overallCostText.setFont(overallCostText.getFont().deriveFont(18f));
        overallCostText.setHorizontalAlignment(overallCostText.CENTER);
        
        
    }
}
